name: easy_gym_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flat_list: ^0.1.14
  page_view_dot_indicator: ^2.1.0
  toast: ^0.3.0
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - lib/recursos/jsons/alunosFeed.json
    - lib/recursos/imagens/user.png
    - lib/recursos/imagens/agachamento.png
    - lib/recursos/imagens/supino.png